backend = "fastresize"
color_space = "lch"
palette = "dark"

[templates]
rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.cache/wallust/colors-rofi.rasi'
waybar.template = 'colors-waybar.css'
waybar.target = '~/.cache/wallust/colors-waybar.css'
swayosd.template = 'colors-swayosd.css'
swayosd.target = '~/.cache/wallust/colors-swayosd.css'
hypr.template = 'colors-hypr.conf'
hypr.target = '~/.cache/wallust/colors-hypr.conf'
kitty.template = 'colors-kitty.conf'
kitty.target = '~/.cache/wallust/colors-kitty.conf'
wlogout.template = 'colors-wlogout.css'
wlogout.target = '~/.cache/wallust/colors-wlogout.css'
nixoslogo.template = 'colors-nixoslogo.svg'
nixoslogo.target = '~/.cache/wallust/colors-nixoslogo.svg'
wlogout-lock.template = 'wlogout/lock.svg'
wlogout-lock.target = '~/.cache/wallust/wlogout/lock.svg'
wlogout-logout.template = 'wlogout/logout.svg'
wlogout-logout.target = '~/.cache/wallust/wlogout/logout.svg'
wlogout-suspend.template = 'wlogout/suspend.svg'
wlogout-suspend.target = '~/.cache/wallust/wlogout/suspend.svg'
wlogout-hibernate.template = 'wlogout/hibernate.svg'
wlogout-hibernate.target = '~/.cache/wallust/wlogout/hibernate.svg'
wlogout-shutdown.template = 'wlogout/shutdown.svg'
wlogout-shutdown.target = '~/.cache/wallust/wlogout/shutdown.svg'
wlogout-reboot.template = 'wlogout/reboot.svg'
wlogout-reboot.target = '~/.cache/wallust/wlogout/reboot.svg'